---
title: "histo_survival_os"
output: html_document
---

```{r}
library(survival)
library(survminer)
library(ggplot2)
library(GGally)
library(data.table)
library(factoextra)
library(readr)
library(readxl)
library(cluster)
library(rstatix)
library(matrixStats)
```


```{r}
Slides2Outcomes_Rapa_all <- read_csv("~/Dog/Slides2Outcomes_Rapa_all_new.csv")
Slides2Outcomes_SOC_all <- read_csv("~/Dog/Slides2Outcomes_SOC_all_new.csv")
dat1 <- subset(Slides2Outcomes_Rapa_all,select = c("slide","Patient ID","Tumor Location","Site","age","weight","breed","gender","PH","ALP","Group","DFI","DFI_censor","Survival (days from sx)","Surv_censor"))
dat1$treatment = rep("Rapamycin", nrow(dat1))
dat2 <- subset(Slides2Outcomes_SOC_all,select = c("slide","Patient ID","Tumor Location","Site","age","weight","breed","gender","PH","ALP","Group","DFI","DFI_censor","Survival (days from sx)","Surv_censor"))
dat2$treatment = rep("SOC", nrow(dat2))

problematic_slides <- read_excel("~/Dog/problematic_slides.xlsx", col_names = FALSE)
problematic_slides$...1 <- sapply(problematic_slides$...1, function(x) gsub("_lowres\\.tiff",".ndpi",x))

#colnames(dat2) <- colnames(dat1)
base <- rbind(dat1,dat2)

clindat_all <- base
clindat_all <- as.data.frame(clindat_all)
clindat_all <- clindat_all[!duplicated(clindat_all$slide),]
rownames(clindat_all) <- substr(clindat_all$slide,1,19)
clindat_all <- clindat_all[,-1]
colnames(clindat_all)[c(11,12,13,14)] <- c("DFS_time","DFS_status","OS_time","OS_status")
clindat_all$ALP[clindat_all$ALP == "elevated"] <- "Elevated"

dog_slide_level_features <- read.csv("~/Downloads/dog_slide_level_features.csv")
rownames(dog_slide_level_features) <- dog_slide_level_features$slide
dog_slide_level_features <- dog_slide_level_features[,-1]
#dog_slide_level_features <- dog_slide_level_features > 0.01

ann_slides = union(list.files('~/Dog/annotations/',pattern = "*.xml"), union(list.files('~/Dog/annotations_new/',pattern = "*.xml"),list.files('~/Dog/annotations_19012022/',pattern = '*.xml')))
ann_slides1 = sapply(ann_slides, function(x) gsub('\\.xml','',x))
ann_vr = unique(c("2021-04-24 09.41.08","2021-04-23 13.45.47","2021-04-22 19.54.02","2021-04-22 21.04.21","2021-04-24 09.53.43","2021-04-22 21.00.02","2021-04-23 10.59.46","2021-04-23 13.50.55"))
ann_fb = unique(c("2021-04-22 20.39.58","2021-04-22 20.03.45","2021-04-22 20.43.04","2021-04-24 09.41.08","2021-04-24 10.51.35","2021-04-23 15.26.57","2021-04-22 14.45.24","2021-04-23 16.04.06","2021-04-23 15.58.26","2021-04-22 20.09.40"))

ann_slides = union(ann_vr, ann_fb)
dd_ann_vr <- dog_slide_level_features[ann_vr,]
dd_ann_fb <- dog_slide_level_features[ann_fb,]

common <- intersect(rownames(clindat_all),rownames(dog_slide_level_features))
clindat_all <- clindat_all[common,]
dog_slide_level_features <- dog_slide_level_features[common,]

clindat_all$annotated <- sapply(common, function(x) x %in% ann_slides1)

dd <- dog_slide_level_features


nslides = as.numeric(table(clindat_all$`Patient ID`))
names(nslides) <- names(table(clindat_all$`Patient ID`))
dd_sum <- rowSums(dd)
dd_patient <- aggregate.data.frame(dd, by = list(as.character(clindat_all$`Patient ID`)), FUN = mean)
#dd_sum_patient <- aggregate.data.frame(dd_sum, by = list(as.character(clindat_all$`Patient ID`)), FUN = sum)
#rownames(dd_sum_patient) <- dd_sum_patient$Group.1
#dd_sum_patient <- dd_sum_patient[,-1]

clindat_all <- clindat_all[!duplicated(clindat_all$`Patient ID`),]
rownames(dd_patient) <- as.character(dd_patient$Group.1)
dd_patient <- dd_patient[,-1]
dd_patient <- dd_patient[as.character(clindat_all$`Patient ID`),]
#dd_sum_patient <- dd_sum_patient[as.character(clindat_all$`Patient ID`),]
#dd_patient <- t(apply(dd_patient, 1, function(x) x/sum(x)))
clindat_all$isFemale <- grepl("female", ignore.case = T, clindat_all$gender)

#dd_patient2 <- t(apply(dd_patient,1,function(x) x/sum(x)))
clindat_all <- cbind(clindat_all, dd_patient)
clindat_all$nslides <- nslides[as.character(clindat_all$`Patient ID`)]
#clindat_all$tumor_burden <- dd_sum_patient$x
```


```{r}
set.seed(1234)
k7 = kmeans(apply(dd_patient,2,scale), centers = 2,nstart = 25)



avg_sil <- function(k, idx) {
  km.res <- kmeans(apply(dd_patient[idx,],2,scale), centers = k, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(apply(dd_patient[idx,],2,scale)))
  mean(ss[, 3])
}

# Compute and plot wss for k = 2 to k = 15
k.values <- c(2:15)

# extract avg silhouette for 2-15 clusters
avg_sil_values <- t(sapply(k.values, function(k) {
  vals <- sapply(1:100, function(x) {
    idx = sample(seq(nrow(dd_patient)),110)
    return(avg_sil(k, idx))
  })
  return(vals)
}))


```

```{r}
mean_sil = rowMeans(avg_sil_values)
sd_sil = rowSds(avg_sil_values)

pp <- ggplot(data = data.frame(K = k.values, score = mean_sil), aes(x=K, y=score)) + 
  geom_line() +
  geom_point() + 
  geom_errorbar(aes(ymin=score-sd_sil, ymax=score+sd_sil), position = position_dodge(0.05), width=0.2) + xlab("Number of Clusters(K)") + ylab("Avg silhouette score") + theme_classic()
pp <- pp + scale_x_continuous(breaks=seq(2,15,1)) + theme(text = element_text(size = 15))

print(pp)
#plot(k.values, avg_sil_values,
#       type = "b", pch = 19, frame = FALSE, 
#       xlab = "Number of clusters K",
#       ylab = "Average Silhouette Score")
pp2 <- fviz_cluster(k7, data = apply(dd_patient,2,scale), repel = TRUE, geom="point") + theme(text = element_text(size = 15)) + theme_classic()
print(pp2)

fig <- ggarrange(pp, pp2, labels = c("A","B"), nrow = 1, ncol = 2)
print(fig)
```


```{r}
c1 <- clindat_all
c1$cluster <- as.character(k7$cluster)
surv <- survfit(Surv(OS_time, OS_status) ~ cluster, data = c1)
diff <- survfit(Surv(OS_time, OS_status) ~ cluster, data = c1)

p1 <- ggsurvplot(surv, data = c1,
                  
                  legend.title = "Dog osteosarcoma overall survival",
                  conf.int = F,
                  pval = TRUE,
                  risk.table = TRUE,
                  tables.height = 0.2,
                  tables.theme = theme_cleantable(),
                  risk.table.y.text = FALSE,
                 pval.coord = c(0, 0.03),
                  # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                  # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
                  ggtheme = theme_bw() # Change ggplot2 theme
) + xlab("Time (days from sx)")

surv <- survfit(Surv(DFS_time, DFS_status) ~ cluster, data = c1)
diff <- survfit(Surv(DFS_time, DFS_status) ~ cluster, data = c1)

p2 <- ggsurvplot(surv, data = c1,
                  legend.title = "Dog osteosarcoma DFI",
                  conf.int = F,
                  pval = TRUE,
                  risk.table = TRUE,
                  tables.height = 0.2,
                  tables.theme = theme_cleantable(),
                  risk.table.y.text = FALSE,
                 pval.coord = c(0, 0.03),
                  # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                  # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
                  ggtheme = theme_bw() # Change ggplot2 theme
)
fig1 <- ggarrange(p1[[1]],p1[[2]], nrow = 2,ncol = 1,heights = c(3,1))
fig2 <- ggarrange(p2[[1]],p2[[2]], nrow = 2,ncol = 1,heights = c(3,1))
print(fig1)
print(fig2)

dist_mat = melt(subset(c1, select = c("CB","FB","GC","HN","OB","VR","cluster")))
colnames(dist_mat) <- c("cluster","variant","area")

stat.test <- dist_mat %>% group_by(variant) %>% t_test(area ~ cluster) %>% add_significance("p") %>% add_xy_position(x = "variant", dodge = 0.8)
bxp <- ggboxplot(
  dist_mat, x = "variant", y = "area", 
  color = "cluster"
  )
p5 <- bxp + stat_pvalue_manual(
  stat.test,  label = "{p.signif}", 
  tip.length = 0, hide.ns = TRUE
  ) +  ylab("Burden (Total area / #slides)") + xlab("subtype")
print(ggarrange(p5, labels = "E", nrow = 1, ncol = 1))


clindat_all <- c1
cph_dat <- data.frame(time = clindat_all$OS_time,
                      status = clindat_all$OS_status,
                      cluster = clindat_all$cluster,
                      location = c("NPH","PH")[as.numeric(clindat_all$PH)+1],
                      ALP = clindat_all$ALP,
                      age = scale(as.numeric(clindat_all$age)),
                      gender = clindat_all$gender,
                      weight = scale(clindat_all$weight),
                      treatment = c("SOC","Sirolimus+SOC")[as.numeric(clindat_all$treatment == "Rapamycin")+1])
cph_dat$gender[grepl("female", ignore.case = T, cph_dat$gender)] = "F"
cph_dat$gender[grepl("male", ignore.case = T, cph_dat$gender)] = "M"
cph_dat$ALP[clindat_all$ALP != "Elevated"] = "Normal"
#cph_dat$isFemale = as.numeric(cph_dat$isFemale == "F")

fit <- coxph(Surv(time, status) ~ location + ALP + age + gender + weight + treatment +  cluster, data = cph_dat)
print(summary(fit))
p3 <- ggforest(fit, data = cph_dat,fontsize = 0.7, noDigits = 2)

cph_dat <- data.frame(time = clindat_all$DFS_time,
                      status = clindat_all$DFS_status,
                      cluster = clindat_all$cluster,
                      location = c("NPH","PH")[as.numeric(clindat_all$PH)+1],
                      ALP = clindat_all$ALP,
                      age = scale(as.numeric(clindat_all$age)),
                      gender = clindat_all$gender,
                      weight = scale(clindat_all$weight),
                      treatment = c("SOC","Sirolimus+SOC")[as.numeric(clindat_all$treatment == "Rapamycin")+1])
cph_dat$gender[grepl("female", ignore.case = T, cph_dat$gender)] = "F"
cph_dat$gender[grepl("male", ignore.case = T, cph_dat$gender)] = "M"
cph_dat$ALP[clindat_all$ALP != "Elevated"] = "Normal"
#cph_dat$isFemale = as.numeric(cph_dat$isFemale == "F")

fit <- coxph(Surv(time, status) ~ location + ALP + age + gender + weight + treatment +  cluster, data = cph_dat)
print(summary(fit))
p4 <- ggforest(fit, data = cph_dat,fontsize = 0.7, noDigits = 2)
print(p3)
print(p4)

#fit2 <- coxph(Surv(time, status) ~ OB +CB +FB+GC+HN+VR + PH + EALP, data = cph_dat)
#p5 <- ggforest(fit2, data = cph_dat,fontsize = 1)
#print(p5)
```

```{r}
cph_dat <- data.frame(time = clindat_all$OS_time,
status = clindat_all$OS_status,
VR = scale(as.numeric(clindat_all$VR)),
FB = scale(as.numeric(clindat_all$FB)),
CB = scale(as.numeric(clindat_all$CB)),
HN = scale(as.numeric(clindat_all$HN)),
OB = scale(as.numeric(clindat_all$OB)),
PH = as.numeric(clindat_all$PH == 1),
EALP = as.numeric(clindat_all$ALP == "Elevated"),
age = scale(as.numeric(clindat_all$age)),
isFemale = clindat_all$gender,
weight = scale(clindat_all$weight))
cph_dat$isFemale[grepl("female", ignore.case = T, cph_dat$isFemale)] = "F"
cph_dat$isFemale = as.numeric(cph_dat$isFemale == "F")
fit <- coxph(Surv(time, status) ~ PH + EALP + age + isFemale+weight + VR, data = cph_dat)
p3 <- ggforest(fit, data = cph_dat,fontsize = 1)
cph_dat <- data.frame(time = clindat_all$DFS_time,
status = clindat_all$DFS_status,
VR = scale(as.numeric(clindat_all$VR)),
FB = scale(as.numeric(clindat_all$FB)),
CB = scale(as.numeric(clindat_all$CB)),
HN = scale(as.numeric(clindat_all$HN)),
OB = scale(as.numeric(clindat_all$OB)),
PH = as.numeric(clindat_all$PH == 1),
EALP = as.numeric(clindat_all$ALP == "Elevated"),
age = scale(as.numeric(clindat_all$age)),
isFemale = clindat_all$gender,
weight = scale(clindat_all$weight))
cph_dat$isFemale[grepl("female", ignore.case = T, cph_dat$isFemale)] = "F"
cph_dat$isFemale = as.numeric(cph_dat$isFemale == "F")
fit <- coxph(Surv(time, status) ~ PH + EALP + age + isFemale+weight + VR, data = cph_dat)
print(summary(fit))
p4 <- ggforest(fit, data = cph_dat,fontsize = 1)
print(p3)
print(p4)
```

```{r}
#by annotations
c1 <- clindat_all
c1$cluster <- as.character(k7$cluster)
c1 = c1[c1$annotated,]
surv <- survfit(Surv(OS_time, OS_status) ~ cluster, data = c1)
diff <- survfit(Surv(OS_time, OS_status) ~ cluster, data = c1)

p1 <- ggsurvplot(surv, data = c1,
                  
                  legend.title = "Dog osteosarcoma overall survival (annotated cases, N = 55)",
                  conf.int = F,
                  pval = TRUE,
                  risk.table = TRUE,
                  tables.height = 0.2,
                  tables.theme = theme_cleantable(),
                  risk.table.y.text = FALSE,
                 pval.coord = c(0, 0.03),
                  # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                  # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
                  ggtheme = theme_bw() # Change ggplot2 theme
) + xlab("Time (days from sx)")

surv <- survfit(Surv(DFS_time, DFS_status) ~ cluster, data = c1)
diff <- survfit(Surv(DFS_time, DFS_status) ~ cluster, data = c1)

p2 <- ggsurvplot(surv, data = c1,
                  legend.title = "Dog osteosarcoma DFI (annotated cases, N = 55)",
                  conf.int = F,
                  pval = TRUE,
                  risk.table = TRUE,
                  tables.height = 0.2,
                  tables.theme = theme_cleantable(),
                  risk.table.y.text = FALSE,
                 pval.coord = c(0, 0.03),
                  # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                  # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
                  ggtheme = theme_bw() # Change ggplot2 theme
)
fig1 <- ggarrange(p1[[1]],p1[[2]], nrow = 2,ncol = 1,heights = c(3,1))
fig2 <- ggarrange(p2[[1]],p2[[2]], nrow = 2,ncol = 1,heights = c(3,1))
print(fig1)
print(fig2)

a1 <- ggarrange(fig1,fig2, labels = c("A","B"), nrow = 1, ncol = 2)

c1 <- clindat_all
c1$cluster <- as.character(k7$cluster)
c1 = c1[!c1$annotated,]
surv <- survfit(Surv(OS_time, OS_status) ~ cluster, data = c1)
diff <- survfit(Surv(OS_time, OS_status) ~ cluster, data = c1)

p1 <- ggsurvplot(surv, data = c1,
                  
                  legend.title = "Dog osteosarcoma overall survival (unannotated cases, N = 218)",
                  conf.int = F,
                  pval = TRUE,
                  risk.table = TRUE,
                  tables.height = 0.2,
                  tables.theme = theme_cleantable(),
                  risk.table.y.text = FALSE,
                 pval.coord = c(0, 0.03),
                  # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                  # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
                  ggtheme = theme_bw() # Change ggplot2 theme
) + xlab("Time (days from sx)")

surv <- survfit(Surv(DFS_time, DFS_status) ~ cluster, data = c1)
diff <- survfit(Surv(DFS_time, DFS_status) ~ cluster, data = c1)

p2 <- ggsurvplot(surv, data = c1,
                  legend.title = "Dog osteosarcoma DFI (unannotated cases, N = 218)",
                  conf.int = F,
                  pval = TRUE,
                  risk.table = TRUE,
                  tables.height = 0.2,
                  tables.theme = theme_cleantable(),
                  risk.table.y.text = FALSE,
                 pval.coord = c(0, 0.03),
                  # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                  # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
                  ggtheme = theme_bw() # Change ggplot2 theme
)
fig1 <- ggarrange(p1[[1]],p1[[2]], nrow = 2,ncol = 1,heights = c(3,1))
fig2 <- ggarrange(p2[[1]],p2[[2]], nrow = 2,ncol = 1,heights = c(3,1))
print(fig1)
print(fig2)

a2 <- ggarrange(fig1,fig2, labels = c("C","D"), nrow = 1, ncol = 2)

sfig2 <- ggarrange(a1,a2, labels = c("",""), nrow = 2, ncol = 1)
ggsave(sfig2, filename = "~/Dog/SuppFig2.pdf", width = 12, height = 12)
```


```{r}
library(ggpubr)
F1 <- ggarrange(fig1,NULL,fig2,p3, NULL,p4, labels = c("A","","B","","", ""), nrow = 2, ncol = 3, widths = c(0.45,0.1,0.45,0.45,0.1,0.45))
#F1 = ggarrange(fig1, p3,fig2,p4, labels = c(D","","E","","F","","G"), ncol = 4,nrow = 1)
#F2 <- ggarrange(F1, p5, labels = c("","E"), nrow = 2, ncol = 1, heights = c(5,2), widths = 6)
print(F1)

fff <- ggarrange(fig, F1, labels = c("",""), nrow = 2, ncol = 1)
print(fff)

ffff <- ggarrange(fig,p5, labels = c("",""), nrow = 2, ncol = 1, heights = c(0.5, 0.5))
print(ffff)

ggsave(ffff, filename = "~/Dog/Fig4_1.pdf", width = 12, height = 10)
ggsave(F1, filename = "~/Dog/Fig4_2.pdf", width = 12, height = 12)
```
```{r}
ddat <- melt(table(clindat_all$cluster, clindat_all$Site))
colnames(ddat) = c("Group","Site","count")
ddat$Group <- as.character(ddat$Group)
p7 <- ggplot(data.frame(ddat), aes(x = Site, y = count)) + geom_bar(stat = "identity") + theme_bw() + theme(axis.text.x = element_text(angle = 90)) + xlab("Institution") + ylab("#cases")
print(p7)

ggsave(p7,filename = "~/Dog/sites.pdf")
chisq.test(table(clindat_all$cluster, clindat_all$Site))
```
```{r}
ddat <- melt(table(clindat_all$cluster, clindat_all$breed))
colnames(ddat) = c("Group","breed","count")
ddat$Group <- as.character(ddat$Group)
ddat$breed <- factor(ddat$breed, levels=names(sort(table(clindat_all$breed), decreasing=TRUE)))
p8 <- ggplot(data.frame(ddat), aes(x = breed, y = count)) + geom_bar(stat = "identity") + theme_bw() + theme(axis.text.x = element_text(angle = 90)) + xlab("Breed") + ylab("#cases")
print(p8)
ggsave(p8,filename = "~/Dog/breeds.pdf")

chisq.test(table(clindat_all$cluster, clindat_all$breed))
```

```{r}
cmat_dog <- matrix(c(117,0,0,12,0,11,35,0,145,0,5,0,32,24,0,0,45,0,0,0,11,8,0,0,430,2,114,94,0,0,0,5,308,8,163,5,5,0,64,35,3522,461,20,26,15,47,39,402,3237), nrow=7)
rownames(cmat_dog) <- c("CB","FB","GC","Necrosis","VR","other","OB")
colnames(cmat_dog) <- c("CB","FB","GC","Necrosis","VR","other","OB")
cc <- as.table(cmat_dog)
names(attr(cc, "dimnames")) <- c("target","prediction")
cfm2 <- as_tibble(cc)
p11 <- plot_confusion_matrix(cfm2,
target_col = "target",
prediction_col = "prediction",
counts_col = "n",add_row_percentages = F, add_col_percentages = F, add_counts = T,add_normalized = F) + theme(text = element_text(size = 15))
percentages = rowSums(cc)/sum(rowSums(cc)) 
positions = c("VR","other","OB","Necrosis","GC","FB","CB")
p111 <- ggplot(data.frame(x = names(percentages), y = percentages), aes(x,y)) + geom_bar(stat = "identity") + scale_x_discrete(limits = positions) + xlab("") + ylab("% of test data") + theme_classic() + theme(text = element_text(size = 15)) +scale_y_continuous(limits = c(0,0.5))
#print(p111)

p11 <- ggarrange(p11,p111, labels = c("",""), nrow = 2, ncol = 1, heights = c(0.5,0.5))
print(p11)


cmat_human <- matrix(c(21,0,0,1,1,2,68,0,1136,0,0,24,7,7,0,7,522,0,0,0,11,3,1,1,3116,154,32,84,1,11,0,84,13711,320,643,7,41,5,99,370,14584,528,73,96,96,276,1276,969,13928), nrow = 7)
rownames(cmat_human) <- c("CB","FB","GC","Necrosis","VR","other","OB")
colnames(cmat_human) <- c("CB","FB","GC","Necrosis","VR","other","OB")
cc2 <- as.table(cmat_human)
names(attr(cc2, "dimnames")) <- c("target","prediction")
cfm3 <- as_tibble(cc2)
p12 <- plot_confusion_matrix(cfm3,
target_col = "target",
prediction_col = "prediction",
counts_col = "n",add_row_percentages = F, add_col_percentages = F, add_counts = T,add_normalized = F) + theme(text = element_text(size = 15))
percentages = rowSums(cc2)/sum(rowSums(cc2)) 
positions = c("VR","other","OB","Necrosis","GC","FB","CB")
p112 <- ggplot(data.frame(x = names(percentages), y = percentages), aes(x,y)) + geom_bar(stat = "identity") + scale_x_discrete(limits = positions) + xlab("") + ylab("% of test data") + theme_classic() + theme(text = element_text(size = 15)) +scale_y_continuous(limits = c(0,0.5))
#print(p111)

p12 <- ggarrange(p12,p112, labels = c("",""), nrow = 2, ncol = 1, heights = c(0.5,0.5))
print(p12)


ffig <- ggarrange(p11, p12, labels = c("A","B"))
print(ffig)

```
```{r}
library(readr)
pred_tab_test_dog <- read_csv("~/Downloads/pred_tab_test_dog.csv")

ce_precisions <- sapply(1:1000, function(x) {
  idx <- sample(seq(nrow(pred_tab_test_dog)), nrow(pred_tab_test_dog)/2)
  boot_strap_tab <- pred_tab_test_dog[idx,]
  cm <- as.matrix(table(boot_strap_tab$labels, boot_strap_tab$predictions)
   )
  precisions <- diag(cm)/colSums(cm)
  return(precisions)
  
})

rownames(ce_precisions) <- c("CB","FB","GC","Necrosis","VR","other","OB")

sd_prec = rowSds(ce_precisions)*100
names(sd_prec) <- rownames(ce_precisions)

ce_recalls <- sapply(1:1000, function(x) {
  idx <- sample(seq(nrow(pred_tab_test_dog)), nrow(pred_tab_test_dog)/2)
  boot_strap_tab <- pred_tab_test_dog[idx,]
  cm <- as.matrix(table(boot_strap_tab$labels, boot_strap_tab$predictions)
   )
  recalls <- diag(cm)/rowSums(cm)
  return(recalls)
  
})

rownames(ce_recalls) <- c("CB","FB","GC","Necrosis","VR","other","OB")
sd_recall = rowSds(ce_recalls)*100
names(sd_recall) <- rownames(ce_recalls)


pred_tab_test_human <- read_csv("~/Downloads/pred_tab_test_human.csv")

ce_precisions2 <- sapply(1:1000, function(x) {
  idx <- sample(seq(nrow(pred_tab_test_human)), nrow(pred_tab_test_human)/2)
  boot_strap_tab <- pred_tab_test_human[idx,]
  cm <- as.matrix(table(boot_strap_tab$labels, boot_strap_tab$predictions)
   )
  precisions <- diag(cm)/colSums(cm)
  return(precisions)
  
})

rownames(ce_precisions2) <- c("CB","FB","GC","Necrosis","VR","other","OB")

sd_prec2 = rowSds(ce_precisions2)*100
names(sd_prec2) <- rownames(ce_precisions2)

ce_recalls2 <- sapply(1:1000, function(x) {
  idx <- sample(seq(nrow(pred_tab_test_human)), nrow(pred_tab_test_human)/2)
  boot_strap_tab <- pred_tab_test_human[idx,]
  cm <- as.matrix(table(boot_strap_tab$labels, boot_strap_tab$predictions)
   )
  recalls <- diag(cm)/rowSums(cm)
  return(recalls)
  
})

rownames(ce_recalls2) <- c("CB","FB","GC","Necrosis","VR","other","OB")
sd_recall2 = rowSds(ce_recalls2)*100
names(sd_recall2) <- rownames(ce_recalls2)
```

```{r}
ce_f1 <- 2*(ce_precisions*ce_recalls)/(ce_precisions+ce_recalls)
ce_f12 <- 2*(ce_precisions2*ce_recalls2)/(ce_precisions2+ce_recalls2)

print(summary(colMeans(ce_f1)))
print(summary(colMeans(ce_f12)))
```


```{r}
positions = c("VR","other","OB","Necrosis","GC","FB","CB")
dd_dog <- data.frame("subtype" = c("VR","other","OB","Necrosis","GC","FB","CB","VR","other","OB","Necrosis","GC","FB","CB"),"metric" = c(rep("Precision",7),rep("Recall",7)),"value" = c(0.8,0.86,0.8,0.76,0.75,0.82,0.78,0.64,0.86,0.85,0.66,0.8,0.7,0.67)*100, sd = c(sd_prec[positions], sd_recall[positions]), stringsAsFactors = F)


p21 <- ggplot(data = dd_dog, aes(x = subtype, y = value, fill = metric)) + geom_bar(stat = "identity", position = "dodge", color = "black") + geom_errorbar(aes(ymin=value-sd, ymax=value+sd), width=.2,position=position_dodge(.9)) + scale_x_discrete(limits = positions) + theme_bw() + theme(text = element_text(size = 15), , axis.text.x = element_text(angle = 90)) + ylab(label = "%") + scale_fill_manual("metric", values = c("Precision" = "orange", "Recall" = "blue2")) + labs(title = "Dogs (test)") + scale_y_continuous(limits = c(0,100))

print(p21)

dd_human <- data.frame("subtype" = c("VR","other","OB","Necrosis","GC","FB","CB","VR","other","OB","Necrosis","GC","FB","CB"),"metric" = c(rep("Precision",7),rep("Recall",7)),"value" = c(0.88,0.92,0.91,0.87,0.84,0.88,0.2,0.93,0.93,0.83,0.92,0.86,0.97,0.23)*100, sd = c(sd_prec2[positions], sd_recall2[positions]), stringsAsFactors = F)

p22 <- ggplot(data = dd_human, aes(x = subtype, y = value, fill = metric)) + geom_bar(stat = "identity", position = "dodge", color = "black") + geom_errorbar(aes(ymin=value-sd, ymax=value+sd), width=.2,position=position_dodge(.9)) + scale_x_discrete(limits = positions) + theme_bw() + theme(text = element_text(size = 15), axis.text.x = element_text(angle = 90)) + ylab(label = "%") + scale_fill_manual("metric", values = c("Precision" = "orange", "Recall" = "blue2")) + labs(title = "Humans (test)") + scale_y_continuous(limits = c(0,100))

print(p22)

ffig2 <- ggarrange(ggarrange(p21, p22, labels = c("C","D")), NULL, labels = c("","E"), nrow = 2, ncol = 1, heights = c(0.5,0.5))
print(ffig)
print(ffig2)
ffig3 <- ggarrange(ffig,ffig2, labels = c("",""), nrow = 1, ncol = 2)
print(ffig3)
ggsave(ffig3, filename = "~/Dog/Fig2.pdf", width = 20, height = 12)


```


```{r}
library(readr)
adv_losses_final <- as.data.frame(read_csv("~/Downloads/adv_losses_final2.csv"))
adv_losses_dog_final <- as.data.frame(read_csv("~/Downloads/adv_losses_dog_final2.csv"))
adv_losses_sds_final <- as.data.frame(read_csv("~/Downloads/adv_losses_sds_final2.csv"))

dd_losses <- melt(adv_losses_final)
colnames(dd_losses) <- c("approach","loss")
dd_losses$epoch <- rep(seq(15),4)

dd_losses_sds <- melt(adv_losses_sds_final)
colnames(dd_losses_sds) <- c("approach","sd")
dd_losses_sds$epoch <- rep(seq(15),4)

dd_losses$sd <- dd_losses_sds$sd
dd_losses$approach = as.character(dd_losses$approach)
# dd_losses$approach[dd_losses$approach == "adv"] = "adversarial learning (trained on dog+human)"
# dd_losses$approach[dd_losses$approach == "noadv"] = "supervised learning (trained on dog+human)"
# dd_losses$approach[dd_losses$approach == "dh"] = "supervised learning (trained on dog data only)"
# dd_losses$approach[dd_losses$approach == "hh"] = "supervised learning (trained on human data only)"

#pp1 <- ggplot(data = dd_losses[dd_losses$approach %in% c("adversarial learning (trained on dog+human)","supervised learning (trained on dog+human)"),], aes(x = epoch, y = loss, color = approach)) + geom_line() + geom_point() + theme_classic() + theme(text = element_text(size = 15)) + scale_x_continuous(limits = c(1,15.5), breaks = seq(1,15,1)) + scale_y_continuous(limits = c(0,1))

pp2 <- ggplot(data = dd_losses, aes(x = epoch, y = loss, color = approach)) + geom_line() + geom_point() + theme_classic() + theme(text = element_text(size = 15)) + ylab(label = "average test error (human)") + scale_x_continuous(limits = c(1,15.5), breaks = seq(1,15,1)) + scale_y_continuous(limits = c(0,2.6), breaks = seq(0,2.6,0.1))

print(pp2)
ggsave(pp2, filename = "~/Dog/adv_losses.pdf", width = 7, height = 5)
#loss_fig <- ggarrange(pp1,pp2, labels = c("",""), nrow = 2, ncol = 1)
#print(loss_fig)
```
```{r}
library(readxl)
Dog_patches <- read_excel("~/Dog/Dog_patches.xlsx")
Dog_patches <- Dog_patches[,-9]
dd_patches <- melt(Dog_patches)
dd_patches$patches <- factor(as.character(dd_patches$patches), levels = c("Train","Validation","Test"))
p99 <- ggplot(data = dd_patches, aes(x = variable, y = value, fill = patches)) + geom_bar(stat = "identity", position = "dodge", color = "black") + theme_classic() + theme(text = element_text(size = 15)) + scale_fill_manual("dataset", values = c("Train"="#004D40", "Validation"="#1E88E5", "Test"="#D81B60")) + ylab("number of WSI patches") + xlab("subtype") + scale_y_continuous(limits = c(0,42000)) + labs(title = "Canine Osteosarcoma (Source Domain)")
print(p99)

library(readxl)
Human_patches <- read_excel("~/Dog/Human_patches.xlsx")
Human_patches <- Human_patches[,-9]
dd_patches <- melt(Human_patches)
dd_patches$patches <- factor(as.character(dd_patches$patches), levels = c("Train","Test"))
p100 <- ggplot(data = dd_patches, aes(x = variable, y = value, fill = patches)) + geom_bar(stat = "identity", position = "dodge", color = "black") + theme_classic() + theme(text = element_text(size = 15)) + scale_fill_manual("dataset", values = c("Train"="#004D40", "Test"="#D81B60")) + ylab("number of WSI patches") + xlab("subtype") + scale_y_continuous(limits = c(0,42000)) + labs(title = "Human Osteosarcoma (Target Domain)")
print(p100)

dat_fig <- ggarrange(p99,p100, labels = c("C","D"), nrow = 2, ncol = 1)
ggsave(dat_fig, filename = "~/Dog/train_val_test_fig.pdf", height = 10, width = 7)
```

